### ISSUE TITLE
invalid character 'j' after top-level value in migrate command

### ISSUE THREAD

**Issue by WatchDogsDev** [arvancloud/cli#18]
Hi,
I'm using v1.2.2 and everything is working fine except paas migrate command.
When I try to use "arvan paas migrate" command I get this error :

```
❯ arvan paas migrate

FAILED: invalid character 'j' after top-level value
```

**Comment by payamQorbanpour** [comment]
Did you have projects on destination region before?
If no, could you please try changing your region to _asiatec(ir-thr-at1)_ using command `arvan paas region` and then try migrate again using command `arvan paas migrate`?

**Comment by WatchDogsDev** [comment]
Running `arvan paas region` and selecting `at1` solved the problem. 
But it's maybe better to handle these errors.
Thanks !

**Comment by payamQorbanpour** [comment]
> Running `arvan paas region` and selecting `at1` solved the problem. But it's maybe better to handle these errors. Thanks !

We already did that in the next releasing patch. Thanks for report.
